version: '3.7'

services:
  api:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
        - 5432
    env_file:
      - ./.env.dev.db

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env.dev.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: