# Generated by Django 4.2.1 on 2024-01-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_assigned_user_task_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hardness',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
