# Generated by Django 4.2.1 on 2024-01-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
